sonar.projectKey=angular-app
sonar.projectName=arcana-angular
sonar.sources=src
sonar.exclusions=dist/**,node_modules/**,**/*.spec.ts,coverage/**,src/scripts/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
